SRCS = main.cpp superaccumulator.c
EXE_NAME = main.out

SOURCES = $(abspath $(SRCS))

OBJECTS := ${SOURCES:.c=.o}
OBJECTS := ${OBJECTS:.cpp=.o}

all: main.out

is_64=$(shell s=`uname -m`; if (echo $$s | grep x86_64 > /dev/null); then echo 1; fi)

CXX = g++
CXXFLAGS=-Wall -W -O3 $(DEFINES:%=-D%) $(INCLUDE) -march=native -fabi-version=0 -fopenmp -masm=intel
# -std=c++11

HOME_LIB=/mnt/data/soft/lib
PATH_TO_INC=$(HOME_LIB)/mpfr/include/ -I$(HOME_LIB)/gmp/include/
PATH_TO_LIB=-L$(HOME_LIB)/mpfr/lib/ -L$(HOME_LIB)/gmp/lib/ -lmpfr -lgmp

main.out:$(OBJECTS)
	$(CXX) $(CXXFLAGS) -I$(PATH_TO_INC) -Wl,-rpath,$(PATH_TO_LIB) -o $@ $(OBJECTS) -L$(PATH_TO_LIB)
	
%.o : %.cpp
	$(CXX) $(CXXFLAGS) -I$(PATH_TO_INC) -Wl,-rpath,$(PATH_TO_LIB) -c $< -L$(PATH_TO_LIB)
	
%.o : %.c
	$(CXX) $(CXXFLAGS) -I$(PATH_TO_INC) -Wl,-rpath,$(PATH_TO_LIB) -c $< -L$(PATH_TO_LIB)

clean:
	rm -f main.out *.o
