#ifndef OCLBLAS_TUNE_PARAMETERS_H_
#define OCLBLAS_TUNE_PARAMETERS_H_

static const int OCLBLAS_DGEMMK_M_WG = 48;
static const int OCLBLAS_DGEMMK_N_WG = 64;
static const int OCLBLAS_DGEMMK_K_WG = 16;
static const int OCLBLAS_DGEMMK_M_WI = 3;
static const int OCLBLAS_DGEMMK_N_WI = 4;
#define OCLBLAS_DGEMMK_USE_CBC_LAYOUT_A
#define OCLBLAS_DGEMMK_USE_RBC_LAYOUT_B

static const int OCLBLAS_DGEMMK_COPYA_M_WG = 24;
static const int OCLBLAS_DGEMMK_COPYA_K_WG = 2;
static const int OCLBLAS_DGEMMK_COPYA_M_WI = 1;
static const int OCLBLAS_DGEMMK_COPYA_K_WI = 2;
static const int OCLBLAS_DGEMMK_COPYA_TRANS_M_WG = 16;
static const int OCLBLAS_DGEMMK_COPYA_TRANS_K_WG = 16;
static const int OCLBLAS_DGEMMK_COPYA_TRANS_M_WI = 1;
static const int OCLBLAS_DGEMMK_COPYA_TRANS_K_WI = 1;
static const int OCLBLAS_DGEMMK_COPYB_N_WG = 32;
static const int OCLBLAS_DGEMMK_COPYB_K_WG = 8;
static const int OCLBLAS_DGEMMK_COPYB_N_WI = 1;
static const int OCLBLAS_DGEMMK_COPYB_K_WI = 8;
static const int OCLBLAS_DGEMMK_COPYB_TRANS_N_WG = 64;
static const int OCLBLAS_DGEMMK_COPYB_TRANS_K_WG = 4;
static const int OCLBLAS_DGEMMK_COPYB_TRANS_N_WI = 1;
static const int OCLBLAS_DGEMMK_COPYB_TRANS_K_WI = 1;

static const int OCLBLAS_DSYMMK_COPY_LEFT_UPPER_M_WG = 8;
static const int OCLBLAS_DSYMMK_COPY_LEFT_UPPER_K_WG = 16;
static const int OCLBLAS_DSYMMK_COPY_LEFT_UPPER_M_WI = 2;
static const int OCLBLAS_DSYMMK_COPY_LEFT_UPPER_K_WI = 1;
static const int OCLBLAS_DSYMMK_COPY_LEFT_LOWER_M_WG = 8;
static const int OCLBLAS_DSYMMK_COPY_LEFT_LOWER_K_WG = 16;
static const int OCLBLAS_DSYMMK_COPY_LEFT_LOWER_M_WI = 2;
static const int OCLBLAS_DSYMMK_COPY_LEFT_LOWER_K_WI = 1;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_UPPER_N_WG = 32;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_UPPER_K_WG = 8;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_UPPER_N_WI = 1;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_UPPER_K_WI = 4;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_LOWER_N_WG = 64;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_LOWER_K_WG = 8;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_LOWER_N_WI = 1;
static const int OCLBLAS_DSYMMK_COPY_RIGHT_LOWER_K_WI = 4;

static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_M_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_K_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_M_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_K_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_TRANS_M_WG = 8;
static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_TRANS_K_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_TRANS_M_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_LEFT_UPPER_TRANS_K_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_M_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_K_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_M_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_K_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_TRANS_M_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_TRANS_K_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_TRANS_M_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_LEFT_LOWER_TRANS_K_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_N_WG = 32;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_K_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_N_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_K_WI = 8;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_TRANS_N_WG = 64;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_TRANS_K_WG = 4;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_TRANS_N_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_UPPER_TRANS_K_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_N_WG = 64;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_K_WG = 16;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_N_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_K_WI = 8;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_TRANS_N_WG = 64;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_TRANS_K_WG = 4;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_TRANS_N_WI = 1;
static const int OCLBLAS_DTRMMK_COPY_RIGHT_LOWER_TRANS_K_WI = 1;

static const int OCLBLAS_SGEMMK_M_WG = 64;
static const int OCLBLAS_SGEMMK_N_WG = 128;
static const int OCLBLAS_SGEMMK_K_WG = 16;
static const int OCLBLAS_SGEMMK_M_WI = 4;
static const int OCLBLAS_SGEMMK_N_WI = 8;
#define OCLBLAS_SGEMMK_USE_CBC_LAYOUT_A
#define OCLBLAS_SGEMMK_USE_RBC_LAYOUT_B

static const int OCLBLAS_SGEMMK_COPYA_M_WG = 32;
static const int OCLBLAS_SGEMMK_COPYA_K_WG = 8;
static const int OCLBLAS_SGEMMK_COPYA_M_WI = 1;
static const int OCLBLAS_SGEMMK_COPYA_K_WI = 8;
static const int OCLBLAS_SGEMMK_COPYA_TRANS_M_WG = 16;
static const int OCLBLAS_SGEMMK_COPYA_TRANS_K_WG = 8;
static const int OCLBLAS_SGEMMK_COPYA_TRANS_M_WI = 1;
static const int OCLBLAS_SGEMMK_COPYA_TRANS_K_WI = 1;
static const int OCLBLAS_SGEMMK_COPYB_N_WG = 128;
static const int OCLBLAS_SGEMMK_COPYB_K_WG = 4;
static const int OCLBLAS_SGEMMK_COPYB_N_WI = 1;
static const int OCLBLAS_SGEMMK_COPYB_K_WI = 4;
static const int OCLBLAS_SGEMMK_COPYB_TRANS_N_WG = 32;
static const int OCLBLAS_SGEMMK_COPYB_TRANS_K_WG = 8;
static const int OCLBLAS_SGEMMK_COPYB_TRANS_N_WI = 1;
static const int OCLBLAS_SGEMMK_COPYB_TRANS_K_WI = 1;

static const int OCLBLAS_SSYMMK_COPY_LEFT_UPPER_M_WG = 16;
static const int OCLBLAS_SSYMMK_COPY_LEFT_UPPER_K_WG = 16;
static const int OCLBLAS_SSYMMK_COPY_LEFT_UPPER_M_WI = 2;
static const int OCLBLAS_SSYMMK_COPY_LEFT_UPPER_K_WI = 1;
static const int OCLBLAS_SSYMMK_COPY_LEFT_LOWER_M_WG = 16;
static const int OCLBLAS_SSYMMK_COPY_LEFT_LOWER_K_WG = 16;
static const int OCLBLAS_SSYMMK_COPY_LEFT_LOWER_M_WI = 2;
static const int OCLBLAS_SSYMMK_COPY_LEFT_LOWER_K_WI = 2;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_UPPER_N_WG = 128;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_UPPER_K_WG = 4;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_UPPER_N_WI = 1;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_UPPER_K_WI = 2;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_LOWER_N_WG = 128;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_LOWER_K_WG = 4;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_LOWER_N_WI = 1;
static const int OCLBLAS_SSYMMK_COPY_RIGHT_LOWER_K_WI = 2;

static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_M_WG = 32;
static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_K_WG = 8;
static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_M_WI = 1;
static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_K_WI = 8;
static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_TRANS_M_WG = 32;
static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_TRANS_K_WG = 8;
static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_TRANS_M_WI = 1;
static const int OCLBLAS_STRMMK_COPY_LEFT_UPPER_TRANS_K_WI = 1;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_M_WG = 64;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_K_WG = 8;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_M_WI = 1;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_K_WI = 4;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_TRANS_M_WG = 32;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_TRANS_K_WG = 8;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_TRANS_M_WI = 1;
static const int OCLBLAS_STRMMK_COPY_LEFT_LOWER_TRANS_K_WI = 1;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_N_WG = 64;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_K_WG = 4;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_N_WI = 1;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_K_WI = 4;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_TRANS_N_WG = 128;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_TRANS_K_WG = 4;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_TRANS_N_WI = 2;
static const int OCLBLAS_STRMMK_COPY_RIGHT_UPPER_TRANS_K_WI = 1;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_N_WG = 128;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_K_WG = 4;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_N_WI = 1;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_K_WI = 4;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_TRANS_N_WG = 128;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_TRANS_K_WG = 4;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_TRANS_N_WI = 2;
static const int OCLBLAS_STRMMK_COPY_RIGHT_LOWER_TRANS_K_WI = 1;

#endif // ifndef OCLBLAS_TUNE_PARAMETERS_H_
